**Numpy**

In [ ]:
#pip install numpy

In [ ]:
import numpy as np

In [ ]:
#create numpy arrays
#Ex - create a array from a python list

Arr = np.array([1,2,3,4])
print(Arr)

[1 2 3 4]


In [ ]:
#zero dimension array - scalar value (one value)

zero_arr = np.array([22])
print(zero_arr)

[22]


In [ ]:
#one dimension array

one_arr = np.array([2,9,3,5])
print(one_arr)

[2 9 3 5]


In [ ]:
#two dimension array

two_arr = np.array([[1,2,3],[4,5,6]])
print(two_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#how to create a 2D array with floating point numbers

matrix_floating = np.array([[0.1,0.2,0.3,0.9],[0.4,0.5,0.6,0.8]])
print(matrix_floating )

[[0.1 0.2 0.3 0.9]
 [0.4 0.5 0.6 0.8]]


In [ ]:
#mathematical operation with 2D array

a=np.array([[1,2],[3,4]])
b=np.array([[9,8],[7,6]])
c=a+b
d=a-b
print(c)
print(d)

[[10 10]
 [10 10]]
[[-8 -6]
 [-4 -2]]


In [ ]:
#how to access element of 2d array using rows & columns using indexing

a = np.array([[1,2],[4,5]])
print(a[1,0])
print(a[0,1])

4
2


In [ ]:
#3D array

three_arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(three_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#how to create 3d arr of floating point numbers

three_arr = np.array([[[1.1,2.2],[3.3,4.4]],[[5.5,6.6],[7.7,8.8]]])
print(three_arr)

[[[1.1 2.2]
  [3.3 4.4]]

 [[5.5 6.6]
  [7.7 8.8]]]


In [ ]:
#0 - scaler
#1 - vector
#2 - matrix
#3 - cube

*Basic array operations*

In [ ]:
#element wise operation like addition , sub , mul , div

a = np.array([1,2,3,4,5])
b = np.array([11,12,13,14,15])
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[12 14 16 18 20]
[-10 -10 -10 -10 -10]
[11 24 39 56 75]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333]


In [ ]:
#scaler operation

a = np.array([6,9,8,7])
print(a*2) #mul 2
print(a**2) #square


[12 18 16 14]
[36 81 64 49]


In [ ]:
#indexing and slicing arr

a = np.array([77,99,88,22])
print(a[-1])
print(a[0:4])

22
[77 99 88 22]


In [ ]:
#array shaping

a = np.array([1,3,5,7,9])
b = np.array([[[1.1,2.2],[3.3,4.4]],[[5.5,6.6],[7.7,8.8]]])
res = a.shape
res1 = b.shape
print(res)
print(res1)

(5,)
(2, 2, 2)
[1 3 5 7 9]


In [ ]:
#array reshaping

a = np.array([1,3,5,7,9,0])
res2 = a.reshape(2,3)
print(res2)

[[1 3 5]
 [7 9 0]]


In [ ]:

c = np.array([[[1.1,2.2],[3.3,4.4]],[[5.5,6.6],[7.7,8.8]]])
res3 = c.reshape(2,4)
res4 = c.reshape(4,2)
print(res3)
print(res4)

[[1.1 2.2 3.3 4.4]
 [5.5 6.6 7.7 8.8]]
[[1.1 2.2]
 [3.3 4.4]
 [5.5 6.6]
 [7.7 8.8]]


*Array functions and operations*

In [ ]:

a = np.array([1,3,5,7,9,0])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))

25
0
9
4.166666666666667
