In [2]:
import numpy as np

In [12]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[1.0,2.0,3.0],[6.0,9.0,5.0]])
print(b)

[[1. 2. 3.]
 [6. 9. 5.]]


In [19]:
#to get dimensions
a.ndim

1

In [12]:
b.ndim

2

In [21]:
#get shape
a.shape


(3,)

In [14]:
b.shape

(2, 3)

In [25]:
a = np.array([1,2,3],dtype='int16')
print(a)
a.dtype

[1 2 3]


dtype('int16')

In [29]:
#get type
a.dtype

dtype('int16')

In [30]:
b.dtype

dtype('float64')

In [24]:
#get size
a.itemsize

2

In [26]:
#get total size
a.size * a.itemsize

6

In [27]:
a.nbytes  #same as total size

6

In [28]:
b.itemsize

8

In [31]:
b.nbytes

48

In [ ]:
#ACESSING / CHANGING SPECIFIC ELEMENTS , ROWS, COLUMNS, ETC

In [33]:
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [35]:
c.shape

(2, 5)

In [39]:
#get a specific element [r,c]

c[1,4]

10

In [40]:
c[0,-1]

5

In [41]:
#get a specific row

c[0,:]

array([1, 2, 3, 4, 5])

In [42]:
#get a specific column

c[:,3]

array([4, 9])

In [44]:
#getting a little more fance [ startindex:endindex:stepsize]
c[0,1:4:2]

array([2, 4])

In [45]:
c[1,4]= 22
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 22]]


In [48]:
c[:,1]= 2
print(c)


[[ 1  2  2  4  5]
 [ 6  2  2  9 22]]


In [49]:
c[:,1] = [11,33]
print(c)

[[ 1 11  2  4  5]
 [ 6 33  2  9 22]]


In [50]:
#3d examples

d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [51]:
#get specific element( work outseide in )

d[0,1,1]

4

In [54]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [55]:
#replace

d[:,0,:] = 10
print(d)

[[[10 10]
  [ 3  4]]

 [[10 10]
  [ 7  8]]]


In [3]:
#initializing different types of arrays

#All 0's matrix

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.zeros((2,3,3,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [7]:
#All 1's matrix 

np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
np.ones((2,2), dtype='int32') 

array([[1, 1],
       [1, 1]])

In [10]:
#Any other numbers

np.full((2,2),99)  #((shape),number)

array([[99, 99],
       [99, 99]])

In [11]:
np.full((2,2),99 , dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [13]:
#any other number(full_like) - take a shape thats already built

np.full(a , 4)

array([[[4, 4, 4],
        [4, 4, 4]]])

In [14]:
#random decimal numbers

np.random.rand(4,2)

array([[0.78881565, 0.78053679],
       [0.51835004, 0.08714916],
       [0.94619134, 0.25417834],
       [0.477249  , 0.99430204]])

In [17]:

np.random.rand(4,2,2)

array([[[0.37912978, 0.26771265],
        [0.37118922, 0.68443963]],

       [[0.73310439, 0.44259147],
        [0.20545715, 0.69978806]],

       [[0.93893408, 0.47675079],
        [0.51721869, 0.92932431]],

       [[0.19014446, 0.0380094 ],
        [0.85896741, 0.47423113]]])

In [18]:

np.random.random_sample(a.shape)  #using shape of a

array([0.50052159, 0.00612349, 0.89376538])

In [20]:
#random integer values

np.random.randint(7,size=(3,3))  #(till which number, size) - 7 is exclusive i.e not included

array([[2, 1, 6],
       [0, 3, 5],
       [1, 0, 2]])

In [21]:
np.random.randint(5,7,size=(3,3))  #(start to till which number, size)

array([[6, 6, 6],
       [5, 6, 6],
       [6, 5, 6]])

In [23]:
#identity matrix

np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [24]:
#repeat an array

arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [26]:

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [30]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
#be careful when copying arrays!!

a = np.array([1,2,3])
b=a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [34]:
a = np.array([1,2,3])
b=a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [40]:
#MATHEMATICS

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [39]:
a + 2

array([3, 4, 5, 6])

In [41]:
a - 2

array([-1,  0,  1,  2])

In [42]:
a * 2


array([2, 4, 6, 8])

In [43]:
a / 2


array([0.5, 1. , 1.5, 2. ])

In [44]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [45]:
a ** 2

array([ 1,  4,  9, 16])

In [46]:
#take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [47]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [54]:
#LINEAR ALGEBRA

a = np.ones((2,4))
print(a)

b = np.full((4,2),2)
print(b)

#a*b shows error as they have diff dimensions

np.matmul(a,b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]]


array([[8., 8.],
       [8., 8.]])

In [55]:
#finding the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

In [56]:
#STATISTICS

stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.min(stats)

1

In [60]:
np.min(stats , axis = 0)

array([1, 2, 3])

In [61]:
np.min(stats , axis = 1)

array([1, 4])

In [62]:
np.max(stats)

6

In [64]:
np.max(stats,axis=0)

array([4, 5, 6])

In [65]:
np.max(stats,axis=1)

array([3, 6])

In [71]:
#REORGANIZING ARRAYS

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)


after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [72]:
#vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [74]:
np.vstack([v1,v1,v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
#horizontally stacking

h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)
np.hstack([h1,h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [79]:
#MISCELLANEOUS

In [85]:
#load data fromm files

filedata = np.genfromtxt('data.txt',delimiter=',')
filedata

In [88]:
filedata = filedata.astype('int32')  #first it's in float then changes to int
filedata

In [ ]:
#BOOLEAN MASKING AND ADVANCED INDEXING

filedata > 50   #shows false or true

filedata [filedata > 50]  #gives the array >50

In [ ]:
#you can index with a list in NumPY

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]  #gives output with number on that index - [2,3,9]

In [ ]:
np.any(filedata>50 , axis=0)

np.all(filedata>50 , axis=0)

In [ ]:

((filedata >50) & (filedata <100))

(~((filedata >50) & (filedata <100)))

In [ ]:
#PRACTICE